const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('sagitari', {
  getConfig: () => ipcRenderer.invoke('config:get'),
  saveProvider: (p) => ipcRenderer.invoke('provider:save', p),
  deleteProvider: (id) => ipcRenderer.invoke('provider:delete', id),
  listModels: (baseUrl, apiKey) => ipcRenderer.invoke('provider:models', { baseUrl, apiKey }),
  activateProvider: (cfg) => ipcRenderer.invoke('provider:activate', cfg),
  setSettings: (patch) => ipcRenderer.invoke('settings:set', patch),
  sendChat: (text, imageDataUrl) => ipcRenderer.invoke('chat:send', { text, imageDataUrl }),
  stopChat: () => ipcRenderer.invoke('chat:stop'),
  clearChat: () => ipcRenderer.invoke('chat:clear'),
  glow: (mode, color) => ipcRenderer.send('glow:set', { mode, color }),
  onAgentEvent: (cb) => ipcRenderer.on('agent:event', (e, ev) => cb(ev)),
  onGlow: (cb) => ipcRenderer.on('glow:set', (e, v) => cb(v)),
  voiceStart: () => ipcRenderer.invoke('voice:start'),
  voiceStop: () => ipcRenderer.invoke('voice:stop'),
  onVoice: (cb) => ipcRenderer.on('voice:partial', (e, t) => cb('partial', t)),
  onVoiceFinal: (cb) => ipcRenderer.on('voice:final', (e, t) => cb('final', t)),
  onVoiceReady: (cb) => ipcRenderer.on('voice:ready', (e, t) => cb('ready', t)),
  onVoiceMode: (cb) => ipcRenderer.on('voice:mode', (e, t) => cb('mode', t)),
  onVoiceHint: (cb) => ipcRenderer.on('voice:hint', (e, t) => cb('hint', t)),
  onVoiceStopped: (cb) => ipcRenderer.on('voice:stopped', () => cb('stopped')),
  onVoiceError: (cb) => ipcRenderer.on('voice:error', (e, t) => cb('error', t)),
  speak: (text) => ipcRenderer.invoke('tts:speak', text),
  quit: () => ipcRenderer.invoke('app:quit'),
  openExternal: (url) => ipcRenderer.invoke('app:openExternal', url),
  minimize: () => ipcRenderer.invoke('app:minimize'),
  maximize: () => ipcRenderer.invoke('app:maximize'),
  onWinState: (cb) => ipcRenderer.on('win:maximized', (e, v) => cb(v)),
  openPath: (p) => ipcRenderer.invoke('shell:openPath', p),
  pickFolder: () => ipcRenderer.invoke('shell:pickFolder'),
  workspaceGet: () => ipcRenderer.invoke('workspace:get'),
  workspaceSet: (dir) => ipcRenderer.invoke('workspace:set', dir),
  workspacePick: () => ipcRenderer.invoke('workspace:pick'),
  memoryList: () => ipcRenderer.invoke('memory:list'),
  skillsList: () => ipcRenderer.invoke('skills:list'),
  skillsToggle: (id, enabled) => ipcRenderer.invoke('skills:toggle', { id, enabled }),
  skillsImport: (repo) => ipcRenderer.invoke('skills:import', repo),
  skillsCreate: (data) => ipcRenderer.invoke('skills:create', data),
  skillsDelete: (id) => ipcRenderer.invoke('skills:delete', id),
  skillsRead: (id) => ipcRenderer.invoke('skills:read', id),
  skillsOpenFolder: () => ipcRenderer.invoke('skills:openFolder'),
  memoryAdd: (text) => ipcRenderer.invoke('memory:add', { text }),
  memoryRemove: (id) => ipcRenderer.invoke('memory:remove', id),
  convList: () => ipcRenderer.invoke('conv:list'),
  convNew: () => ipcRenderer.invoke('conv:new'),
  convOpen: (id) => ipcRenderer.invoke('conv:open', id),
  convRename: (title) => ipcRenderer.invoke('conv:rename', title),
  convDel: (id) => ipcRenderer.invoke('conv:del', id),
  setMode: (m) => ipcRenderer.invoke('mode:set', m),
  getAgentsLive: () => ipcRenderer.invoke('agents:live')
});
