const { contextBridge, ipcRenderer, webUtils } = require('electron');

/* Suscripción con baja. Cada on* devuelve la función que la cancela: sin ella,
   volver a llamar a un on* (reinit del renderer, recableado de estado) dejaba
   dos listeners vivos y el mismo evento se atendía dos veces. */
const on = (channel, make) => (cb) => {
  const h = (e, ...args) => cb(...make(args));
  ipcRenderer.on(channel, h);
  return () => ipcRenderer.removeListener(channel, h);
};

contextBridge.exposeInMainWorld('sagitari', {
  // Electron ≥32 eliminó File.path: la ruta real de un archivo soltado/pegado
  // sólo se obtiene por aquí (compatible con sandbox: true)
  filePath: (file) => webUtils.getPathForFile(file),
  getConfig: () => ipcRenderer.invoke('config:get'),
  saveProvider: (p) => ipcRenderer.invoke('provider:save', p),
  deleteProvider: (id) => ipcRenderer.invoke('provider:delete', id),
  listModels: (baseUrl, apiKey) => ipcRenderer.invoke('provider:models', { baseUrl, apiKey }),
  activateProvider: (cfg) => ipcRenderer.invoke('provider:activate', cfg),
  setSettings: (patch) => ipcRenderer.invoke('settings:set', patch),
  sendChat: (text, imageDataUrl, attachments) => ipcRenderer.invoke('chat:send', { text, imageDataUrl, attachments }),
  attachmentsPick: () => ipcRenderer.invoke('attachments:pick'),
  attachmentsRead: (p) => ipcRenderer.invoke('attachments:read', p),
  stopChat: () => ipcRenderer.invoke('chat:stop'),
  retryChat: () => ipcRenderer.invoke('chat:retry'),
  clearChat: () => ipcRenderer.invoke('chat:clear'),
  glow: (mode, color) => ipcRenderer.send('glow:set', { mode, color }),
  onAgentEvent: on('agent:event', ([ev]) => [ev]),
  onGlow: on('glow:set', ([v]) => [v]),
  voiceStart: () => ipcRenderer.invoke('voice:start'),
  voiceStop: () => ipcRenderer.invoke('voice:stop'),
  onVoice: on('voice:partial', ([t]) => ['partial', t]),
  onVoiceFinal: on('voice:final', ([t]) => ['final', t]),
  onVoiceReady: on('voice:ready', ([t]) => ['ready', t]),
  onVoiceMode: on('voice:mode', ([t]) => ['mode', t]),
  onVoiceHint: on('voice:hint', ([t]) => ['hint', t]),
  onVoiceStopped: on('voice:stopped', () => ['stopped']),
  onVoiceError: on('voice:error', ([t]) => ['error', t]),
  speak: (text) => ipcRenderer.invoke('tts:speak', text),
  onTtsDone: on('tts:done', () => []),
  onThemeChanged: on('theme:changed', ([v]) => [v]),
  quit: () => ipcRenderer.invoke('app:quit'),
  openExternal: (url) => ipcRenderer.invoke('app:openExternal', url),
  minimize: () => ipcRenderer.invoke('app:minimize'),
  maximize: () => ipcRenderer.invoke('app:maximize'),
  onWinState: on('win:maximized', ([v]) => [v]),
  openPath: (p) => ipcRenderer.invoke('shell:openPath', p),
  openDataDir: () => ipcRenderer.invoke('app:openDataDir'),
  pickFolder: () => ipcRenderer.invoke('shell:pickFolder'),
  workspaceGet: () => ipcRenderer.invoke('workspace:get'),
  workspaceSet: (dir) => ipcRenderer.invoke('workspace:set', dir),
  workspacePick: () => ipcRenderer.invoke('workspace:pick'),
  memoryList: () => ipcRenderer.invoke('memory:list'),
  memoryAdd: (text, importance) => ipcRenderer.invoke('memory:add', { text, importance }),
  memoryUpdate: (id, patch) => ipcRenderer.invoke('memory:update', { id, patch }),
  memoryRemove: (id) => ipcRenderer.invoke('memory:remove', id),
  tasksList: () => ipcRenderer.invoke('tasks:list'),
  taskEnqueue: (data) => ipcRenderer.invoke('tasks:enqueue', data),
  taskPause: (runId) => ipcRenderer.invoke('tasks:pause', runId),
  taskResume: (runId) => ipcRenderer.invoke('tasks:resume', runId),
  taskCancel: (runId) => ipcRenderer.invoke('tasks:cancel', runId),
  taskRemove: (runId) => ipcRenderer.invoke('tasks:remove', runId),
  pauseChat: () => ipcRenderer.invoke('chat:pause'),
  skillsList: () => ipcRenderer.invoke('skills:list'),
  skillsToggle: (id, enabled) => ipcRenderer.invoke('skills:toggle', { id, enabled }),
  skillsImport: (repo) => ipcRenderer.invoke('skills:import', repo),
  skillsCreate: (data) => ipcRenderer.invoke('skills:create', data),
  skillsDelete: (id) => ipcRenderer.invoke('skills:delete', id),
  skillsSearch: (q) => ipcRenderer.invoke('skills:search', q),
  skillsUpdate: (id) => ipcRenderer.invoke('skills:update', id),
  skillsUpdateAll: () => ipcRenderer.invoke('skills:updateAll'),
  marketCatalog: () => ipcRenderer.invoke('market:catalog'),
  marketSearch: (q) => ipcRenderer.invoke('market:search', q),
  healthGet: () => ipcRenderer.invoke('health:get'),
  habitsGet: () => ipcRenderer.invoke('habits:get'),
  habitsReset: () => ipcRenderer.invoke('habits:reset'),
  skillsRead: (id) => ipcRenderer.invoke('skills:read', id),
  skillsOpenFolder: () => ipcRenderer.invoke('skills:openFolder'),
  convList: () => ipcRenderer.invoke('conv:list'),
  convNew: () => ipcRenderer.invoke('conv:new'),
  convOpen: (id) => ipcRenderer.invoke('conv:open', id),
  convRename: (title) => ipcRenderer.invoke('conv:rename', title),
  convDel: (id) => ipcRenderer.invoke('conv:del', id),
  setMode: (m) => ipcRenderer.invoke('mode:set', m),
  getAgentsLive: () => ipcRenderer.invoke('agents:live'),
  secResolve: (id, approved, runId) => ipcRenderer.invoke('sec:resolve', { id, approved, runId }),
  secSetToolPerm: (tool, level) => ipcRenderer.invoke('sec:setToolPerm', { tool, level }),
  secSetGuardrail: (patch) => ipcRenderer.invoke('sec:setGuardrail', patch),
  metaGet: () => ipcRenderer.invoke('meta:get'),
  logsRecent: (n) => ipcRenderer.invoke('logs:recent', n),
  updateCheck: () => ipcRenderer.invoke('update:check'),
  updateDownload: () => ipcRenderer.invoke('update:download'),
  updateInstall: () => ipcRenderer.invoke('update:install'),
  updatePage: () => ipcRenderer.invoke('update:page'),
  onUpdate: on('update:event', ([ev]) => [ev]),

  // ---- v3.1: servidores MCP del usuario ----
  mcpList: () => ipcRenderer.invoke('mcp:list'),
  mcpSave: (server) => ipcRenderer.invoke('mcp:save', server),
  mcpDelete: (id) => ipcRenderer.invoke('mcp:delete', id),
  mcpToggle: (id, enabled) => ipcRenderer.invoke('mcp:toggle', { id, enabled }),
  mcpSetGlobal: (enabled) => ipcRenderer.invoke('mcp:setGlobal', enabled),
  mcpTest: (id) => ipcRenderer.invoke('mcp:test', id),
  mcpRefresh: (id) => ipcRenderer.invoke('mcp:refresh', id),
  mcpLog: (id) => ipcRenderer.invoke('mcp:log', id),
  mcpImport: (json) => ipcRenderer.invoke('mcp:import', json),
  mcpExport: () => ipcRenderer.invoke('mcp:export')
});
